# Configuration settings for the bot

# Telegram settings
TELEGRAM_TOKEN = "YOUR_TELEGRAM_TOKEN"

# LinkedIn settings
ACCESS_TOKEN = "YOUR_TOKEN_OAUTH2_LINKEDIN"

# Azure OpenAI settings
AZURE_API_BASE = "YOUR_AZURE_OPENAI_API_BASE"
AZURE_API_KEY = "YOUR_AZURE_OPENAI_API_KEY"
AZURE_REDUNDANCY_API_BASE = "YOUR_AZURE_REDUNDANCY_API_BASE"
AZURE_REDUNDANCY_API_KEY = "YOUR_AZURE_REDUNDANCY_API_KEY"
GPT_MODEL_TURBO = "YOUR_NAME_MODEL_AZURE"
