# RSS feed URLs and names

feed_urls = {
    "/startcustomblog": "https://customblog.com/rss",
    "/azurefeeds": "https://azure.microsoft.com/en-us/blog/feed/",
    "/startazureaiservices": "https://azure.microsoft.com/en-us/blog/topics/ai/feed/",
    "/plainenglishai": "https://plainenglish.io/blog/tag/artificial-intelligence/rss",
    "/startserverless": "https://serverless.com/blog/rss",
    "/startnielskok": "https://nielskok.tech/rss",
    "/startEducatordeveloper": "https://techcommunity.microsoft.com/t5/educator-developer-blog/bg-p/EducatorDeveloperBlog/rss",
    "/startlandingpage": "https://landingpage.com/rss",
    "/startcommandline": "https://commandline.com/rss",
    "/startinfrastructure": "https://infrastructure.com/rss",
    "/azuregovernanceandmanagement": "https://techcommunity.microsoft.com/t5/azure-governance-and-management/bg-p/AzureGovernanceManagement/rss",
    "/microsoftentra": "https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad/bg-p/MicrosoftEntra/rss",
    "/infrastructuresecurity": "https://techcommunity.microsoft.com/t5/infrastructure-security/bg-p/InfrastructureSecurity/rss",
    "/securitycomplianceidentity": "https://techcommunity.microsoft.com/t5/security-compliance-and-identity/bg-p/SecurityComplianceIdentity/rss",
    "/fasttrackforazure": "https://techcommunity.microsoft.com/t5/fasttrack-for-azure/bg-p/FastTrackforAzure/rss",
    "/appsonazureblog": "https://techcommunity.microsoft.com/t5/apps-on-azure-blog/bg-p/AppsOnAzureBlog/rss",
    "/windowsitpro": "https://techcommunity.microsoft.com/t5/windows-it-pro-blog/bg-p/WindowsITProBlog/rss",
    "/itopstalkblog": "https://techcommunity.microsoft.com/t5/it-ops-talk-blog/bg-p/ITOpsTalkBlog/rss",
    "/adamtheautomator": "https://adamtheautomator.com/rss",
    "/thelazyadministrator": "https://thelazyadministrator.com/rss",
    "/powershellcommunity": "https://powershellcommunity.com/rss",
    "/powershellteam": "https://devblogs.microsoft.com/powershell/feed/",
    "/lazyadmin": "https://lazyadmin.nl/rss",
    "/planetpowershell": "https://planetpowershell.com/rss",
    "/startmikefrobbins": "https://mikefrobbins.com/rss",
    "/lukegeek": "https://lukegeek.com/rss",
    "/practical365": "https://practical365.com/rss",
    "/startmicrosoft365": "https://techcommunity.microsoft.com/t5/microsoft-365-blog/bg-p/Microsoft365Blog/rss",
    "/wedoazure": "https://wedoazure.com/rss",
    "/charbelnemnom": "https://charbelnemnom.com/rss",
    "/powershellisfun": "https://powershellisfun.com/rss",
    "/azureappService": "https://techcommunity.microsoft.com/t5/azure-app-service-blog/bg-p/AzureAppServiceBlog/rss",
    "/ourcloudnetwork": "https://ourcloudnetwork.com/rss",
    "/natehutchinson": "https://natehutchinson.com/rss",
    "/techielass": "https://techielass.com/rss",
    "/oceanleaf": "https://oceanleaf.com/rss",
    "/microsoftlearn": "https://techcommunity.microsoft.com/t5/microsoft-learn-blog/bg-p/MicrosoftLearnBlog/rss",
    "/prajwaldesai": "https://prajwaldesai.com/rss",
    "/admindroid": "https://admindroid.com/rss",
    "/danielchronlund": "https://danielchronlund.com/rss",
    "/cswrld": "https://cswrld.com/rss",
    "/cloudarchitekt": "https://cloudarchitekt.com/rss",
    "/office365itpros": "https://office365itpros.com/rss",
    "/emsroute": "https://emsroute.com/rss",
    "/suryendub": "https://suryendub.com/rss",
    "/cloudbrothers": "https://cloudbrothers.com/rss",
}

feed_names = {
    "Custom Blog": "/startcustomblog",
    "Azure Feeds": "/azurefeeds",
    "Azure AI Services": "/startazureaiservices",
    "Plain English AI": "/plainenglishai",
    "Serverless": "/startserverless",
    "NielShok": "/startnielskok",
    "Educator Developer": "/startEducatordeveloper",
    "Landing Page": "/startlandingpage",
    "Command Line": "/startcommandline",
    "Infrastructure": "/startinfrastructure",
    "Azure Governance MGMT": "/azuregovernanceandmanagement",
    "Microsoft Entra (Azure AD)": "/microsoftentra",
    "Infrastructure Security": "/infrastructuresecurity",
    "Sec, Compliance Identity": "/securitycomplianceidentity",
    "FastTrack for Azure": "/fasttrackforazure",
    "Apps on Azure Blog": "/appsonazureblog",
    "Windows IT Pro": "/windowsitpro",
    "IT OpsTalk Blog": "/itopstalkblog",
    "Adam the Automator": "/adamtheautomator",
    "The Lazy Administrator": "/thelazyadministrator",
    "PowerShell Community": "/powershellcommunity",
    "PowerShell Team": "/powershellteam",
    "Lazy Admin": "/lazyadmin",
    "Planet PowerShell": "/planetpowershell",
    "Mike F Robbins": "/startmikefrobbins",
    "Luke Geek": "/lukegeek",
    "Practical 365": "/practical365",
    "Microsoft 365": "/startmicrosoft365",
    "We Do Azure": "/wedoazure",
    "Charbel Nemnom": "/charbelnemnom",
    "Powershell LisFun": "/powershellisfun",
    "Azure App Service": "/azureappService",
    "Our Cloud Network": "/ourcloudnetwork",
    "Nate Hutchinson": "/natehutchinson",
    "Techie Lass": "/techielass",
    "Ocean Leaf": "/oceanleaf",
    "Microsoft Learn": "/microsoftlearn",
    "Prajwal Desai": "/prajwaldesai",
    "AdminDroid": "/admindroid",
    "Daniel Chronlund": "/danielchronlund",
    "CSWrld": "/cswrld",
    "Cloud Architekt": "/cloudarchitekt",
    "Office 365 IT Pros": "/office365itpros",
    "EMS Route": "/emsroute",
    "Suryendu B": "/suryendub",
    "Cloud Brothers": "/cloudbrothers",
}
